# Ref: https://github.com/rt-net/pico_micro_ros_arduino_examples/blob/main/.github/workflows/compile-sketches.yaml

name: Compile Sketches

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  # It's convenient to set variables for values used multiple times in the workflow
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports

jobs:
  compile-sketches:
    strategy:
      matrix:
        env:
          - { FQBN: m5stack-core-esp32, NEED_REPORT: true }
          - { FQBN: stamp-s3, NEED_REPORT: false }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: m5stack:esp32:${{ env.FQBN }}
          platforms: |  # M5Stack公式のpackage indexを使用する
            - name: m5stack:esp32
              version: 2.0.7
              source-url: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
          libraries: |  
            - source-url: https://github.com/m5stack/M5Unified/archive/refs/tags/0.1.9.zip
            - source-url: https://github.com/m5stack/M5GFX/archive/refs/tags/0.1.9.zip
          sketch-paths: |
            - vssl_main

      # This step is needed to pass the size data to the report job 
      - name: Upload sketches report to workflow artifact
        if: ${{ env.NEED_REPORT }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

  report:
    needs: compile-sketches  # Wait for the compile job to finish to get the data for the report
    if: github.event_name == 'pull_request' # Only run the job when the workflow is triggered by a pull request
    runs-on: ubuntu-latest
    steps:
      # This step is needed to get the size data produced by the compile jobs
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
